# Generated by Django 6.1 on 2026-08-07 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_entree', models.DateField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locataires', to='locations.bien')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Utiliser le 1er jour du mois, ex: 2026-08-01')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('retard', 'En retard'), ('partiel', 'Partiel')], default='retard', max_length=10)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='locations.locataire')),
            ],
            options={
                'unique_together': {('locataire', 'mois')},
            },
        ),
    ]
