# Generated by Django 5.2.17 on 2026-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_bien_code_postal_bien_informations_supplementaires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='locataire',
            name='garant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='locataire',
            name='garant_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locataire',
            name='garant_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='locataire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
